env:
  browser: true
  es6: true
  node: true

extends:
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - react-app

plugins:
  - react

rules:
  '@typescript-eslint/explicit-function-return-type':
    - warn
    - allowExpressions: true
  react/prop-types: off
